jobs:
- job: Build
  timeoutInMinutes: 240
  pool:
    vmImage: 'windows-2019'
  steps:
  - script: |
      rd /s /q "C:\Program Files (x86)\Android"
      FOR /f "tokens=*" %%i IN ('docker ps -aq') DO docker rm %%i
      FOR /f "tokens=*" %%i IN ('docker images --format "{{.ID}}"') DO docker rmi %%i
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '2.7' 
      addToPath: true 
      architecture: 'x64'
  - script: |
      call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
      pip install typing wheel pyyaml
      set USE_CUDA=0
      set MSSdk=1
      set FORCE_PY27_BUILD=1
      git submodule update --init --recursive
      python setup.py install
      python setup.py bdist_wheel
